Feat/#9 2 create real
kc3hack/2023_C pull request #30
Opened 2023-02-15 07:43 UTC by TAN-21-den

Real一応完成しました

2023-02-15 07:57 UTC, yu195 requested changes
コンフリクトを解消できていません
最新のmainをマージしてください

2023-02-15 08:06 UTC, yu195 requested changes

2023-02-15 08:06 UTC, yu195 commented on calculator-for-iPad.core/Sources/CalculatorCore/Real.swift
> +        self.isInteger = isExponents
`isInteger`は整数であることを表しています。valが整数のときだけtrueにするようにしてください。また、initは
`init(value: Decimal)`だけにしてください。また、nanを表すpublicなstaticプロパティ用意してnanを返す時はそれを利用するようにしてください。

2023-02-15 08:06 UTC, yu195 commented on calculator-for-iPad.core/Sources/CalculatorCore/Real.swift
> +    }
divideとかもそうですが、左と右が逆です

2023-02-15 08:06 UTC, yu195 commented on calculator-for-iPad.core/Sources/CalculatorCore/Real.swift
> +    var value: Decimal
うまく実装すれば変更する必要はないはずです。letで宣言しましょう。また、valueはprivateで問題ないと思います。

2023-02-15 08:06 UTC, yu195 commented on calculator-for-iPad.core/Sources/CalculatorCore/Real.swift
> +public struct NumberReal: Number{
`NumberReal`より`RealNumber`のほうがいいと思います。ファイル名も変えてください。

2023-02-15 08:36 UTC, yu195 requested changes

2023-02-15 08:36 UTC, yu195 commented on calculator-for-iPad.core/Sources/CalculatorCore/Real.swift
> +    }
下のようにすればいちいち`var`で宣言する必要がないと思うのですがだめなのでしょうか
```swift
public func arcsin(isExponents: Bool) -> Number {
let doubleValue = Double(truncating: value as NSNumber)
return NumberReal(val: Decimal(Foundation.asin(doubleValue)))
}
```

2023-02-15 08:36 UTC, yu195 commented on calculator-for-iPad.core/Sources/CalculatorCore/Number.swift
> +    func modulus(left: Number ,isExponents: Bool) -> Number
必要のない変更が入っています

2023-02-15 08:36 UTC, yu195 commented on calculator-for-iPad.core/Sources/CalculatorCore/Real.swift
> +    }
他の関数でもそうですが、`init(val: Decimal)`を常に使うようにしてください。varで宣言する必要はありません。

2023-02-15 08:36 UTC, yu195 commented on calculator-for-iPad.core/Sources/CalculatorCore/Real.swift
> +    private static let pi_two: Decimal = Decimal.pi / 2
必要なところで定義してください

2023-02-15 08:54 UTC, yu195 requested changes

2023-02-15 08:54 UTC, yu195 commented on calculator-for-iPad.core/Sources/CalculatorCore/Real.swift
> +        if real.value.isNaN || exp.isNaN { return Decimal.nan as! Number }
NumberはDecimalのサブクラスではないため`Decimal.nan as! Number`でキャストできないのではないですか？

2023-02-15 14:54 UTC, yu195 requested changes

2023-02-15 14:54 UTC, yu195 commented on calculator-for-iPad.core/Sources/CalculatorCore/RealNumber.swift
> +        return RealNumber(val: Decimal( myDouble))
これだと誤差が生じるので直接文字列からdecimalに変換してください

2023-02-15 15:40 UTC, TAN-21-den commented on calculator-for-iPad.core/Sources/CalculatorCore/Real.swift
> +        if real.value.isNaN || exp.isNaN { return Decimal.nan as! Number }
直しました

2023-02-15 15:40 UTC, TAN-21-den commented on calculator-for-iPad.core/Sources/CalculatorCore/Real.swift
> +    private static let pi_two: Decimal = Decimal.pi / 2
直しました

2023-02-15 15:41 UTC, TAN-21-den commented on calculator-for-iPad.core/Sources/CalculatorCore/RealNumber.swift
> +        return RealNumber(val: Decimal( myDouble))
直しました

2023-02-15 15:41 UTC, TAN-21-den commented on calculator-for-iPad.core/Sources/CalculatorCore/Real.swift
> +    var value: Decimal
直しました

2023-02-15 15:41 UTC, TAN-21-den commented on calculator-for-iPad.core/Sources/CalculatorCore/Real.swift
> +    }
直しました

2023-02-16 08:38 UTC, yu195 commented on calculator-for-iPad.core/Sources/CalculatorCore/Real.swift
> +    var value: Decimal
letで宣言してください

2023-02-16 08:40 UTC, yu195 commented on calculator-for-iPad.core/Sources/CalculatorCore/Number.swift
> +    func modulus(left: Number ,isExponents: Bool) -> Number
まだ入っています

2023-02-16 08:41 UTC, miyaji255 commented on calculator-for-iPad.core/Sources/CalculatorCore/RealNumber.swift
> +        return RealNumber(val: Decimal( myDouble))
decがnilのときの判定ができていません必ず数字が入るわけではないのでnilのときはNanValueを返すようにしてください

2023-02-16 08:47 UTC, yu195 requested changes
まだまだvarは消せるのですが一旦この2つを修正してもらったら終わりにします

2023-02-16 08:47 UTC, yu195 commented on calculator-for-iPad.core/Sources/CalculatorCore/Number/NanValue.swift
> +        return self.toReal()
self.toReal()とすると無限ループになります。RealNumber(val: .nan)を返してください

2023-02-16 08:47 UTC, yu195 commented on calculator-for-iPad.core/Tests/CalculatorCoreTests/_023_CTests.swift
> +import XCTest
_023_CTests.swiftは消してください

2023-02-16 09:05 UTC, TAN-21-den commented on calculator-for-iPad.core/Sources/CalculatorCore/Number/NanValue.swift
> +        return self.toReal()
修正しました

2023-02-16 09:05 UTC, TAN-21-den commented on calculator-for-iPad.core/Tests/CalculatorCoreTests/_023_CTests.swift
> +import XCTest
消しました

2023-02-16 09:16 UTC, yu195 commented on calculator-for-iPad.core/Sources/CalculatorCore/Number.swift
> +    func modulus(left: Number ,isExponents: Bool) -> Number
まだ入っています

2023-02-16 09:40 UTC, yu195 approved these changes

2023-02-16 09:41 UTC, merged